// Root ESLint flat config (ESLint 9+). Applies to apps/web and packages/*.
// apps/api, apps/worker, and services/* are Python — linted by Ruff instead (see pyproject.toml).
import js from "@eslint/js";
import next from "@next/eslint-plugin-next";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

export default tseslint.config(
  {
    ignores: [
      "**/.next/**",
      "**/dist/**",
      "**/build/**",
      "**/node_modules/**",
      "**/.turbo/**",
      "services/**",
      "apps/api/**",
      "apps/worker/**",
      "docs/**",
      // Without this, ESLint's default recursive discovery walks into the Python
      // venv and lints random vendored .js fixtures inside site-packages (confirmed
      // by actually running `eslint .` from the repo root, not assumed).
      ".venv/**",
      // Auto-generated by Next.js on every build/dev run — never hand-edited, and
      // its triple-slash reference is Next's own required convention, not a lint issue.
      "apps/web/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/consistent-type-imports": "error",
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },
  {
    // Scoped to apps/web only — @next/eslint-plugin-next's rules assume a Next.js
    // App Router project structure that doesn't apply to packages/*.
    files: ["apps/web/**/*.{ts,tsx}"],
    plugins: {
      "@next/next": next,
    },
    rules: {
      ...next.configs.recommended.rules,
      ...next.configs["core-web-vitals"].rules,
    },
  },
);
