"""A reusable base for the common "one prompt, one model call" capability
shape — not every capability needs this (one with no AI step at all just
implements the `Capability` protocol directly), but this covers the shape
without every AI-backed capability hand-rolling the same render-then-route-
then-wrap logic.

Class attributes, not constructor args: CapabilityRegistry stores
`type[Capability]` and CapabilityExecutor instantiates it with zero
arguments, so a subclass configures itself declaratively at the class level,
not through __init__ — there is no constructor seam to inject a template key
through.
"""

from __future__ import annotations

from abc import ABC
from typing import Any, ClassVar

from forgeai_capability_registry.exceptions import CapabilityExecutionError
from forgeai_capability_registry.sdk import CapabilityContext, CapabilityResult
from forgeai_model_router.types import CompletionRequest, ModelMessage, Role
from forgeai_prompts.template import PromptTemplate


class PromptDrivenCapability(ABC):
    """Subclasses set `template_key`/`template_version` to identify which
    registered PromptTemplate to render, and may override `build_output()` if
    their output_schema expects something other than `{"text": ...}`."""

    template_key: ClassVar[str]
    template_version: ClassVar[str]

    async def execute(
        self, context: CapabilityContext, input_data: dict[str, Any]
    ) -> CapabilityResult:
        capability_id = self._capability_id(context)
        if context.prompt_registry is None:
            raise CapabilityExecutionError(capability_id, "no prompt_registry attached to context")
        if context.model_router is None:
            raise CapabilityExecutionError(capability_id, "no model_router attached to context")
        if context.capability_definition is None:
            raise CapabilityExecutionError(capability_id, "no capability_definition on context")

        template = self._resolve_template(context)
        rendered = template.render({key: str(value) for key, value in input_data.items()})

        response = await context.model_router.complete(
            context.capability_definition.supported_models,
            CompletionRequest(messages=[ModelMessage(role=Role.USER, content=rendered)]),
        )

        return CapabilityResult(
            output=self.build_output(response.text),
            reasoning_summary=(
                f"Generated by model '{response.model_key}' in {response.attempts} attempt(s)."
            ),
        )

    def build_output(self, text: str) -> dict[str, Any]:
        return {"text": text}

    def _resolve_template(self, context: CapabilityContext) -> PromptTemplate:
        assert context.prompt_registry is not None  # narrowed by execute()'s own check above
        return context.prompt_registry.get(self.template_key, self.template_version)

    def _capability_id(self, context: CapabilityContext) -> str:
        if context.capability_definition is not None:
            return context.capability_definition.id
        return self.template_key
