"""stage execution retry_after

Revision ID: 6bfaba45831f
Revises: cfa3479fae2b
Create Date: 2026-08-07 23:20:53.798023

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bfaba45831f"
down_revision: str | None = "cfa3479fae2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflow_stage_executions",
        sa.Column("retry_after", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_stage_executions", "retry_after")
    # ### end Alembic commands ###
