"""memory engine structured and episodic memory

Revision ID: cef8e58d0a23
Revises: f0a06220c14f
Create Date: 2026-08-13 23:23:21.558760

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cef8e58d0a23"
down_revision: str | None = "f0a06220c14f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "architecture_decisions",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("context", sa.Text(), nullable=False),
        sa.Column("decision", sa.Text(), nullable=False),
        sa.Column("consequences", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "ACCEPTED",
                "SUPERSEDED",
                "REJECTED",
                name="architecturedecisionstatus",
                native_enum=False,
                length=16,
            ),
            server_default="proposed",
            nullable=False,
        ),
        sa.Column("superseded_by_id", sa.UUID(), nullable=True),
        sa.Column("capability_execution_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_architecture_decisions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_architecture_decisions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["superseded_by_id"],
            ["architecture_decisions.id"],
            name=op.f("fk_architecture_decisions_superseded_by_id_architecture_decisions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_architecture_decisions")),
    )
    op.create_index(
        op.f("ix_architecture_decisions_project_id"),
        "architecture_decisions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_architecture_decisions_status"), "architecture_decisions", ["status"], unique=False
    )
    op.create_table(
        "memory_events",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_memory_events_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memory_events")),
    )
    op.create_index(
        op.f("ix_memory_events_created_at"), "memory_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_memory_events_event_type"), "memory_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_memory_events_project_id"), "memory_events", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_memory_events_project_id"), table_name="memory_events")
    op.drop_index(op.f("ix_memory_events_event_type"), table_name="memory_events")
    op.drop_index(op.f("ix_memory_events_created_at"), table_name="memory_events")
    op.drop_table("memory_events")
    op.drop_index(op.f("ix_architecture_decisions_status"), table_name="architecture_decisions")
    op.drop_index(op.f("ix_architecture_decisions_project_id"), table_name="architecture_decisions")
    op.drop_table("architecture_decisions")
    # ### end Alembic commands ###
