"""workflow persistence

Revision ID: cfa3479fae2b
Revises: da7249485c82
Create Date: 2026-08-04 13:17:16.283376

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cfa3479fae2b"
down_revision: str | None = "da7249485c82"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflows",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_workflows_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflows")),
    )
    op.create_index(op.f("ix_workflows_key"), "workflows", ["key"], unique=True)
    op.create_table(
        "workflow_templates",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "default_input",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_featured", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_templates_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_templates")),
    )
    op.create_index(
        op.f("ix_workflow_templates_workflow_id"),
        "workflow_templates",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "workflow_versions",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("graph_spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_versions_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_versions")),
        sa.UniqueConstraint("workflow_id", "version", name="uq_workflow_version"),
    )
    op.create_index(
        op.f("ix_workflow_versions_workflow_id"), "workflow_versions", ["workflow_id"], unique=False
    )
    op.create_table(
        "workflow_executions",
        sa.Column("workflow_id", sa.UUID(), nullable=False),
        sa.Column("workflow_version_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "PENDING",
                "RUNNING",
                "PAUSED",
                "WAITING_APPROVAL",
                "RETRYING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                "ARCHIVED",
                name="workflowstatus",
                native_enum=False,
                length=32,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "input", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("current_stage_key", sa.String(length=128), nullable=True),
        sa.Column("started_by", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_workflow_executions_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["started_by"],
            ["users.id"],
            name=op.f("fk_workflow_executions_started_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
            name=op.f("fk_workflow_executions_workflow_id_workflows"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_workflow_executions_workflow_version_id_workflow_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_executions")),
    )
    op.create_index(
        op.f("ix_workflow_executions_project_id"),
        "workflow_executions",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_status"), "workflow_executions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_executions_workflow_id"),
        "workflow_executions",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_executions_workflow_version_id"),
        "workflow_executions",
        ["workflow_version_id"],
        unique=False,
    )
    op.create_table(
        "workflow_stages",
        sa.Column("workflow_version_id", sa.UUID(), nullable=False),
        sa.Column("stage_key", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sequence_index", sa.Integer(), nullable=False),
        sa.Column(
            "depends_on",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("capability_key", sa.String(length=128), nullable=True),
        sa.Column(
            "retry_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "timeout_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("requires_approval", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("allow_skip", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_version_id"],
            ["workflow_versions.id"],
            name=op.f("fk_workflow_stages_workflow_version_id_workflow_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_stages")),
        sa.UniqueConstraint("workflow_version_id", "stage_key", name="uq_workflow_stage_key"),
    )
    op.create_index(
        op.f("ix_workflow_stages_workflow_version_id"),
        "workflow_stages",
        ["workflow_version_id"],
        unique=False,
    )
    op.create_table(
        "workflow_events",
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name=op.f("fk_workflow_events_workflow_execution_id_workflow_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_events")),
    )
    op.create_index(
        op.f("ix_workflow_events_created_at"), "workflow_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_events_event_type"), "workflow_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_events_workflow_execution_id"),
        "workflow_events",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_table(
        "workflow_metrics",
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("total_duration_seconds", sa.Float(), nullable=True),
        sa.Column("queue_wait_seconds", sa.Float(), nullable=True),
        sa.Column("stages_completed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("stages_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retries_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name=op.f("fk_workflow_metrics_workflow_execution_id_workflow_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_metrics")),
    )
    op.create_index(
        op.f("ix_workflow_metrics_workflow_execution_id"),
        "workflow_metrics",
        ["workflow_execution_id"],
        unique=True,
    )
    op.create_table(
        "workflow_queue",
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "QUEUED", "CLAIMED", "DONE", name="queueentrystatus", native_enum=False, length=16
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_by", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name=op.f("fk_workflow_queue_workflow_execution_id_workflow_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_queue")),
    )
    op.create_index(op.f("ix_workflow_queue_status"), "workflow_queue", ["status"], unique=False)
    op.create_index(
        op.f("ix_workflow_queue_workflow_execution_id"),
        "workflow_queue",
        ["workflow_execution_id"],
        unique=True,
    )
    op.create_table(
        "workflow_stage_executions",
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("workflow_stage_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "WAITING_APPROVAL",
                "RETRYING",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                "CANCELLED",
                name="stagestatus",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column(
            "input", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attempt_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name=op.f("fk_workflow_stage_executions_workflow_execution_id_workflow_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_stage_id"],
            ["workflow_stages.id"],
            name=op.f("fk_workflow_stage_executions_workflow_stage_id_workflow_stages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_stage_executions")),
    )
    op.create_index(
        op.f("ix_workflow_stage_executions_status"),
        "workflow_stage_executions",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_stage_executions_workflow_execution_id"),
        "workflow_stage_executions",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_stage_executions_workflow_stage_id"),
        "workflow_stage_executions",
        ["workflow_stage_id"],
        unique=False,
    )
    op.create_table(
        "workflow_approvals",
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("stage_execution_id", sa.UUID(), nullable=True),
        sa.Column("requested_from_role", sa.String(length=32), nullable=True),
        sa.Column("requested_from_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "decision",
            sa.Enum(
                "APPROVE",
                "REJECT",
                "REQUEST_CHANGES",
                "ESCALATE",
                "TIMEOUT",
                name="approvaldecision",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("decided_by_id", sa.UUID(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"],
            ["users.id"],
            name=op.f("fk_workflow_approvals_decided_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_from_user_id"],
            ["users.id"],
            name=op.f("fk_workflow_approvals_requested_from_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_execution_id"],
            ["workflow_stage_executions.id"],
            name=op.f("fk_workflow_approvals_stage_execution_id_workflow_stage_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name=op.f("fk_workflow_approvals_workflow_execution_id_workflow_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_approvals")),
    )
    op.create_index(
        op.f("ix_workflow_approvals_stage_execution_id"),
        "workflow_approvals",
        ["stage_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_approvals_workflow_execution_id"),
        "workflow_approvals",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_table(
        "workflow_artifacts",
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("stage_execution_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("artifact_type", sa.String(length=64), nullable=False),
        sa.Column(
            "content", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_execution_id"],
            ["workflow_stage_executions.id"],
            name=op.f("fk_workflow_artifacts_stage_execution_id_workflow_stage_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name=op.f("fk_workflow_artifacts_workflow_execution_id_workflow_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_artifacts")),
    )
    op.create_index(
        op.f("ix_workflow_artifacts_stage_execution_id"),
        "workflow_artifacts",
        ["stage_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_artifacts_workflow_execution_id"),
        "workflow_artifacts",
        ["workflow_execution_id"],
        unique=False,
    )
    op.create_table(
        "workflow_logs",
        sa.Column("workflow_execution_id", sa.UUID(), nullable=False),
        sa.Column("stage_execution_id", sa.UUID(), nullable=True),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stage_execution_id"],
            ["workflow_stage_executions.id"],
            name=op.f("fk_workflow_logs_stage_execution_id_workflow_stage_executions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name=op.f("fk_workflow_logs_workflow_execution_id_workflow_executions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_logs")),
    )
    op.create_index(
        op.f("ix_workflow_logs_created_at"), "workflow_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_workflow_logs_stage_execution_id"),
        "workflow_logs",
        ["stage_execution_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workflow_logs_workflow_execution_id"),
        "workflow_logs",
        ["workflow_execution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_logs_workflow_execution_id"), table_name="workflow_logs")
    op.drop_index(op.f("ix_workflow_logs_stage_execution_id"), table_name="workflow_logs")
    op.drop_index(op.f("ix_workflow_logs_created_at"), table_name="workflow_logs")
    op.drop_table("workflow_logs")
    op.drop_index(
        op.f("ix_workflow_artifacts_workflow_execution_id"), table_name="workflow_artifacts"
    )
    op.drop_index(op.f("ix_workflow_artifacts_stage_execution_id"), table_name="workflow_artifacts")
    op.drop_table("workflow_artifacts")
    op.drop_index(
        op.f("ix_workflow_approvals_workflow_execution_id"), table_name="workflow_approvals"
    )
    op.drop_index(op.f("ix_workflow_approvals_stage_execution_id"), table_name="workflow_approvals")
    op.drop_table("workflow_approvals")
    op.drop_index(
        op.f("ix_workflow_stage_executions_workflow_stage_id"),
        table_name="workflow_stage_executions",
    )
    op.drop_index(
        op.f("ix_workflow_stage_executions_workflow_execution_id"),
        table_name="workflow_stage_executions",
    )
    op.drop_index(
        op.f("ix_workflow_stage_executions_status"), table_name="workflow_stage_executions"
    )
    op.drop_table("workflow_stage_executions")
    op.drop_index(op.f("ix_workflow_queue_workflow_execution_id"), table_name="workflow_queue")
    op.drop_index(op.f("ix_workflow_queue_status"), table_name="workflow_queue")
    op.drop_table("workflow_queue")
    op.drop_index(op.f("ix_workflow_metrics_workflow_execution_id"), table_name="workflow_metrics")
    op.drop_table("workflow_metrics")
    op.drop_index(op.f("ix_workflow_events_workflow_execution_id"), table_name="workflow_events")
    op.drop_index(op.f("ix_workflow_events_event_type"), table_name="workflow_events")
    op.drop_index(op.f("ix_workflow_events_created_at"), table_name="workflow_events")
    op.drop_table("workflow_events")
    op.drop_index(op.f("ix_workflow_stages_workflow_version_id"), table_name="workflow_stages")
    op.drop_table("workflow_stages")
    op.drop_index(
        op.f("ix_workflow_executions_workflow_version_id"), table_name="workflow_executions"
    )
    op.drop_index(op.f("ix_workflow_executions_workflow_id"), table_name="workflow_executions")
    op.drop_index(op.f("ix_workflow_executions_status"), table_name="workflow_executions")
    op.drop_index(op.f("ix_workflow_executions_project_id"), table_name="workflow_executions")
    op.drop_table("workflow_executions")
    op.drop_index(op.f("ix_workflow_versions_workflow_id"), table_name="workflow_versions")
    op.drop_table("workflow_versions")
    op.drop_index(op.f("ix_workflow_templates_workflow_id"), table_name="workflow_templates")
    op.drop_table("workflow_templates")
    op.drop_index(op.f("ix_workflows_key"), table_name="workflows")
    op.drop_table("workflows")
    # ### end Alembic commands ###
