"""drop workflow queue execution id uniqueness

Revision ID: e85ae5cf68b0
Revises: 6bfaba45831f
Create Date: 2026-08-08 00:36:54.179350

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e85ae5cf68b0"
down_revision: str | None = "6bfaba45831f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_queue_workflow_execution_id"), table_name="workflow_queue")
    op.create_index(
        op.f("ix_workflow_queue_workflow_execution_id"),
        "workflow_queue",
        ["workflow_execution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workflow_queue_workflow_execution_id"), table_name="workflow_queue")
    op.create_index(
        op.f("ix_workflow_queue_workflow_execution_id"),
        "workflow_queue",
        ["workflow_execution_id"],
        unique=True,
    )
    # ### end Alembic commands ###
