"""model router persistence

Revision ID: f0a06220c14f
Revises: e85ae5cf68b0
Create Date: 2026-08-11 23:38:47.196516

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0a06220c14f"
down_revision: str | None = "e85ae5cf68b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_profiles",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=255), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("context_window", sa.Integer(), nullable=False),
        sa.Column("supports_tools", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "supports_structured_output", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("cost_per_1m_input", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("cost_per_1m_output", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_profiles")),
    )
    op.create_index(op.f("ix_model_profiles_key"), "model_profiles", ["key"], unique=True)
    op.create_table(
        "usage_ledger",
        sa.Column("model_profile_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("workflow_execution_id", sa.UUID(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_profile_id"],
            ["model_profiles.id"],
            name=op.f("fk_usage_ledger_model_profile_id_model_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_usage_ledger_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_usage_ledger_project_id_projects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_execution_id"],
            ["workflow_executions.id"],
            name=op.f("fk_usage_ledger_workflow_execution_id_workflow_executions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_ledger")),
    )
    op.create_index(
        op.f("ix_usage_ledger_created_at"), "usage_ledger", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_usage_ledger_model_profile_id"), "usage_ledger", ["model_profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_ledger_organization_id"), "usage_ledger", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_ledger_project_id"), "usage_ledger", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_usage_ledger_workflow_execution_id"),
        "usage_ledger",
        ["workflow_execution_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_ledger_workflow_execution_id"), table_name="usage_ledger")
    op.drop_index(op.f("ix_usage_ledger_project_id"), table_name="usage_ledger")
    op.drop_index(op.f("ix_usage_ledger_organization_id"), table_name="usage_ledger")
    op.drop_index(op.f("ix_usage_ledger_model_profile_id"), table_name="usage_ledger")
    op.drop_index(op.f("ix_usage_ledger_created_at"), table_name="usage_ledger")
    op.drop_table("usage_ledger")
    op.drop_index(op.f("ix_model_profiles_key"), table_name="model_profiles")
    op.drop_table("model_profiles")
    # ### end Alembic commands ###
